#!/bin/bash

#####
# put this file in /usr/local/bin and chmod +x the script
#####
STATUS="$1"

#Isolate the id of the touch device automatically.
rawID=`xsetwacom --list | grep --line-buffered "TOUCH" | cut -d':' -f2 | grep -o "[0-9]\+"`
#Trim further
device=`echo "$rawID"`

xsetwacom --set $device touch $1

case $1 in
    on)
        echo "Tablet touch is ENABLED."
        ;;
    off)
        echo "Tablet touch is DISABLED."
        ;;
    *)
        echo "Invalid option. Must be either on or off."
        ;;
esac
